from staples_detection.base.staple_detection_methods import StapleDetectionMethod
from staples_detection.base.result.gradient_staple_detection_result import GradientStapleDetectionResult
from staples_detection.base.result.canny_staple_detection_result import CannyStapleDetectionResult
from staples_detection.staple_detector import StapleDetector
