from .core import Diff as Diff, MarkdownGenerator as MarkdownGenerator
from typing import List, Tuple

class TocGenerator(MarkdownGenerator):
    block_start: str = ...
    def generate_content(self, original_lines: List[str], file_path: str) -> Tuple[str, Diff]: ...
    def get_toc(self, file_path: str) -> str: ...
