RUSSIAN = 0.0529
RUSSE = RUSSIAN

SERBIAN = 0.0643
SERBE = SERBIAN

SWEDISH = 0.0644
SUEDOIS = SWEDISH

ENGLISH = 0.0667
ANGLAIS = ENGLISH

ESPERANTO = 0.0690

GREEK = 0.0691
GREC = GREEK

NORWEGIAN = 0.0694
NORVEGIEN = NORWEGIAN

DANISH = 0.0707
DANOIS = DANISH

FINNISH = 0.0737
FINNOIS = FINNISH

ITALIAN = 0.0738
ITALIEN = ITALIAN

PORTUGUESE = 0.0745
PORTUGAIS = PORTUGUESE

ARABIC = 0.0758
ARABE = ARABIC

GERMAN = 0.0762
ALLEMAND = GERMAN

HEBREW = 0.0768
HEBREU = HEBREW

SPANISH = 0.0770
ESPAGNOL = SPANISH

JAPANESE = 0.0772
JAPONAIS = JAPANESE

FRENCH = 0.0778
FRANCAIS = FRENCH

DUTCH = 0.0798
NEERLANDAIS = DUTCH

MALAYSIAN = 0.0852
MALAYSIEN = MALAYSIAN

IC_eq = {
    RUSSIAN: 'RUSSIAN',
    SERBIAN: 'SERBIAN',
    SWEDISH: 'SWEDISH',
    ENGLISH: 'ENGLISH',
    ESPERANTO: 'ESPERANTO',
    GREEK: 'GREEK',
    NORWEGIAN: 'NORWEGIAN',
    DANISH: 'DANISH',
    FINNISH: 'FINNISH',
    ITALIAN: 'ITALIAN',
    PORTUGUESE: 'PORTUGUESE',
    ARABIC: 'ARABIC',
    GERMAN: 'GERMAN',
    HEBREW: 'HEBREW',
    SPANISH: 'SPANISH',
    JAPANESE: 'JAPANESE',
    FRENCH: 'FRENCH',
    DUTCH: 'DUTCH',
    MALAYSIAN: 'MALAYSIAN'
}

IC_eq_fr = {
    RUSSIAN: 'Russe',
    SERBIAN: 'Serbe',
    SWEDISH: 'Suédois',
    ENGLISH: 'Anglais',
    ESPERANTO: 'Esperanto',
    GREEK: 'Grec',
    NORWEGIAN: 'Norvégien',
    DANISH: 'Danois',
    FINNISH: 'Finnois',
    ITALIAN: 'Italien',
    PORTUGUESE: 'Portugais',
    ARABIC: 'Arabe',
    GERMAN: 'Allemand',
    HEBREW: 'Hébreu',
    SPANISH: 'Espagnol',
    JAPANESE: 'Japonais',
    FRENCH: 'Français',
    DUTCH: 'Néerlandais',
    MALAYSIAN: 'Malaysien'
}
