
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-30T23:06:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d5bd07431e516f17d756a2673f8cf1bd5985464",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
