ENV_NAME = "AIDONODE_NAME"
ENV_DATA_IN = "AIDONODE_DATA_IN"
ENV_DATA_OUT = "AIDONODE_DATA_OUT"
ENV_META_IN = "AIDONODE_META_IN"
ENV_META_OUT = "AIDONODE_META_OUT"
ENV_TRANSLATE = "AIDONODE_TRANSLATE"
# ENV_ENCODING = "AIDONODE_ENCODING"
ENV_CONFIG = "AIDONODE_CONFIG"
ENV_AIDO_REQUIRE_GPU = "AIDO_REQUIRE_GPU"
# ENV_ENCODING_JSON = 'json'
# ENV_ENCODING_CBOR = 'cbor'
# ENV_ENCODING_VALID = [ENV_ENCODING_JSON, ENV_ENCODING_CBOR]
KNOWN = [
    ENV_DATA_IN,
    ENV_DATA_OUT,
    ENV_CONFIG,
    ENV_META_IN,
    ENV_META_OUT,
    ENV_NAME,
    ENV_TRANSLATE,
    ENV_AIDO_REQUIRE_GPU,
    # ENV_ENCODING,
]
TAG_Z2 = "z2"

ATT_CONFIG = "config"


TOPIC_ABORTED = "aborted"

FIELD_COMPAT = "compat"
CUR_PROTOCOL = "z2"

FIELD_DATA = "data"
FIELD_TOPIC = "topic"
FIELD_TIMING = "timing"

FIELD_CONTROL = "control"

CTRL_CAPABILITIES = "capabilities"
CTRL_UNDERSTOOD = "understood"
CTRL_NOT_UNDERSTOOD = "not-understood"
CTRL_OVER = "over"
CTRL_ABORTED = "aborted"

CAPABILITY_PROTOCOL_REFLECTION = "protocol-reflection"
