__title__ = 'executors'
__description__ = 'Job scheduling abstractions'
__url__ = 'https://github.com/harvard-nrg/executors'
__version__ = '0.5.1'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
