depends = ('ITKPyBase', 'ITKStatistics', )
templates = (
  ('SingleValuedCostFunction', 'itk::SingleValuedCostFunction', 'itkSingleValuedCostFunction', True),
  ('SingleValuedVnlCostFunctionAdaptor', 'itk::SingleValuedVnlCostFunctionAdaptor', 'itkSingleValuedVnlCostFunctionAdaptor', True),
  ('MultipleValuedCostFunction', 'itk::MultipleValuedCostFunction', 'itkMultipleValuedCostFunction', True),
  ('MultipleValuedVnlCostFunctionAdaptor', 'itk::MultipleValuedVnlCostFunctionAdaptor', 'itkMultipleValuedVnlCostFunctionAdaptor', True),
  ('CumulativeGaussianCostFunction', 'itk::CumulativeGaussianCostFunction', 'itkCumulativeGaussianCostFunction', True),
  ('Optimizer', 'itk::Optimizer', 'itkOptimizer', True),
  ('NonLinearOptimizer', 'itk::NonLinearOptimizer', 'itkNonLinearOptimizer', True),
  ('SingleValuedNonLinearOptimizer', 'itk::SingleValuedNonLinearOptimizer', 'itkSingleValuedNonLinearOptimizer', True),
  ('SingleValuedNonLinearVnlOptimizer', 'itk::SingleValuedNonLinearVnlOptimizer', 'itkSingleValuedNonLinearVnlOptimizer', True),
  ('MultipleValuedNonLinearOptimizer', 'itk::MultipleValuedNonLinearOptimizer', 'itkMultipleValuedNonLinearOptimizer', True),
  ('MultipleValuedNonLinearVnlOptimizer', 'itk::MultipleValuedNonLinearVnlOptimizer', 'itkMultipleValuedNonLinearVnlOptimizer', True),
  ('ConjugateGradientOptimizer', 'itk::ConjugateGradientOptimizer', 'itkConjugateGradientOptimizer', True),
  ('LBFGSOptimizer', 'itk::LBFGSOptimizer', 'itkLBFGSOptimizer', True),
  ('LevenbergMarquardtOptimizer', 'itk::LevenbergMarquardtOptimizer', 'itkLevenbergMarquardtOptimizer', True),
  ('OnePlusOneEvolutionaryOptimizer', 'itk::OnePlusOneEvolutionaryOptimizer', 'itkOnePlusOneEvolutionaryOptimizer', True),
  ('QuaternionRigidTransformGradientDescentOptimizer', 'itk::QuaternionRigidTransformGradientDescentOptimizer', 'itkQuaternionRigidTransformGradientDescentOptimizer', True),
  ('RegularStepGradientDescentBaseOptimizer', 'itk::RegularStepGradientDescentBaseOptimizer', 'itkRegularStepGradientDescentBaseOptimizer', True),
  ('VersorTransformOptimizer', 'itk::VersorTransformOptimizer', 'itkVersorTransformOptimizer', True),
  ('AmoebaOptimizer', 'itk::AmoebaOptimizer', 'itkAmoebaOptimizer', True),
  ('CumulativeGaussianOptimizer', 'itk::CumulativeGaussianOptimizer', 'itkCumulativeGaussianOptimizer', True),
  ('ExhaustiveOptimizer', 'itk::ExhaustiveOptimizer', 'itkExhaustiveOptimizer', True),
  ('LBFGSBOptimizer', 'itk::LBFGSBOptimizer', 'itkLBFGSBOptimizer', True),
  ('PowellOptimizer', 'itk::PowellOptimizer', 'itkPowellOptimizer', True),
  ('VersorRigid3DTransformOptimizer', 'itk::VersorRigid3DTransformOptimizer', 'itkVersorRigid3DTransformOptimizer', True),
  ('ParticleSwarmOptimizerBase', 'itk::ParticleSwarmOptimizerBase', 'itkParticleSwarmOptimizerBase', True),
  ('ParticleSwarmOptimizer', 'itk::ParticleSwarmOptimizer', 'itkParticleSwarmOptimizer', True),
  ('InitializationBiasedParticleSwarmOptimizer', 'itk::InitializationBiasedParticleSwarmOptimizer', 'itkInitializationBiasedParticleSwarmOptimizer', True),
  ('FRPROptimizerEnums', 'itk::FRPROptimizerEnums', 'itkFRPROptimizerEnums', False),
  ('FRPROptimizer', 'itk::FRPROptimizer', 'itkFRPROptimizer', True),
  ('SPSAOptimizerEnums', 'itk::SPSAOptimizerEnums', 'itkSPSAOptimizerEnums', False),
  ('SPSAOptimizer', 'itk::SPSAOptimizer', 'itkSPSAOptimizer', True),
  ('GradientDescentOptimizerEnums', 'itk::GradientDescentOptimizerEnums', 'itkGradientDescentOptimizerEnums', False),
  ('GradientDescentOptimizer', 'itk::GradientDescentOptimizer', 'itkGradientDescentOptimizer', True),
  ('RegularStepGradientDescentBaseOptimizerEnums', 'itk::RegularStepGradientDescentBaseOptimizerEnums', 'itkRegularStepGradientDescentBaseOptimizerEnums', False),
  ('RegularStepGradientDescentOptimizer', 'itk::RegularStepGradientDescentOptimizer', 'itkRegularStepGradientDescentOptimizer', True),
  ('CostFunctionTemplate', 'itk::CostFunctionTemplate', 'itkCostFunctionTemplateD', False, 'double'),
  ('CostFunctionTemplate', 'itk::CostFunctionTemplate', 'itkCostFunctionTemplateF', False, 'float'),
)
snake_case_functions = ()
