
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-02T12:04:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "898072d8f82ae173457506fa0b2b15a88d8fdf98",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
