# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risefor_lobbying', '0009_auto_20200622_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiongroup',
            name='twitterMessage',
            field=models.ManyToManyField(related_name='twitter_message', to='risefor_lobbying.TwitterMessage'),
        ),
    ]
