#!/usr/bin/env python

"""
https://github.com/trending/LANGUAGE
https://github.com/topics/LANGUAGE

https://github.com/collections/programming-languages

https://github.com/ozh/github-colors/blob/master/colors.json
"""

COLORS = {
    "1C Enterprise": "#814CCC",
    "ABAP": "#E8274B",
    "ActionScript": "#882B0F",
    "Ada": "#02f88c",
    "Agda": "#315665",
    "AGS Script": "#B9D9FF",
    "Alloy": "#64C800",
    "Alpine Abuild": None,
    "AMPL": "#E6EFBB",
    "AngelScript": "#C7D7DC",
    "ANTLR": "#9DC3FF",
    "Apex": None,
    "API Blueprint": "#2ACCA8",
    "APL": "#5A8164",
    "Apollo Guidance Computer": None,
    "AppleScript": "#101F1F",
    "Arc": "#aa2afe",
    "ASP": "#6a40fd",
    "AspectJ": "#a957b0",
    "Assembly": "#6E4C13",
    "Asymptote": "#4a0c0c",
    "ATS": "#1ac620",
    "Augeas": None,
    "AutoHotkey": "#6594b9",
    "AutoIt": "#1C3552",
    "Awk": None,
    "Ballerina": "#FF5000",
    "Batchfile": "#C1F12E",
    "Befunge": None,
    "Bison": None,
    "BitBake": None,
    "BlitzBasic": None,
    "BlitzMax": "#cd6400",
    "Bluespec": None,
    "Boo": "#d4bec1",
    "Brainfuck": "#2F2530",
    "Brightscript": None,
    "Bro": None,
    "C": "#555555",
    "C#": "#178600",
    "C++": "#f34b7d",
    "C2hs Haskell": None,
    "Cap'n Proto": None,
    "CartoCSS": None,
    "Ceylon": "#dfa535",
    "Chapel": "#8dc63f",
    "Charity": None,
    "ChucK": None,
    "Cirru": "#ccccff",
    "Clarion": "#db901e",
    "Clean": "#3F85AF",
    "Click": "#E4E6F3",
    "CLIPS": None,
    "Clojure": "#db5855",
    "CMake": None,
    "COBOL": None,
    "CoffeeScript": "#244776",
    "ColdFusion": "#ed2cd6",
    "ColdFusion CFC": None,
    "Common Lisp": "#3fb68b",
    "Common Workflow Language": "#B5314C",
    "Component Pascal": "#B0CE4E",
    "Cool": None,
    "Coq": None,
    "Crystal": "#000100",
    "Csound": None,
    "Csound Document": None,
    "Csound Score": None,
    "CSS": "#563d7c",
    "Cuda": "#3A4E3A",
    "CWeb": None,
    "Cycript": None,
    "Cython": None,
    "D": "#ba595e",
    "Dart": "#00B4AB",
    "DataWeave": "#003a52",
    "DIGITAL Command Language": None,
    "DM": "#447265",
    "Dockerfile": "#384d54",
    "Dogescript": "#cca760",
    "DTrace": None,
    "Dylan": "#6c616e",
    "E": "#ccce35",
    "eC": "#913960",
    "ECL": "#8a1267",
    "ECLiPSe": None,
    "Eiffel": "#946d57",
    "Elixir": "#6e4a7e",
    "Elm": "#60B5CC",
    "Emacs Lisp": "#c065db",
    "EmberScript": "#FFF4F3",
    "EQ": "#a78649",
    "Erlang": "#B83998",
    "F#": "#b845fc",
    "F*": "#572e30",
    "Factor": "#636746",
    "Fancy": "#7b9db4",
    "Fantom": "#14253c",
    "Filebench WML": None,
    "Filterscript": None,
    "fish": None,
    "FLUX": "#88ccff",
    "Forth": "#341708",
    "Fortran": "#4d41b1",
    "FreeMarker": "#0050b2",
    "Frege": "#00cafe",
    "Game Maker Language": "#71b417",
    "GAMS": None,
    "GAP": None,
    "GCC Machine Description": None,
    "GDB": None,
    "GDScript": "#355570",
    "Genie": "#fb855d",
    "Genshi": None,
    "Gentoo Ebuild": None,
    "Gentoo Eclass": None,
    "Gherkin": "#5B2063",
    "GLSL": None,
    "Glyph": "#c1ac7f",
    "Gnuplot": "#f0a9f0",
    "Go": "#00ADD8",
    "Golo": "#88562A",
    "Gosu": "#82937f",
    "Grace": None,
    "Grammatical Framework": "#79aa7a",
    "Groovy": "#e69f56",
    "Groovy Server Pages": None,
    "Hack": "#878787",
    "Harbour": "#0e60e3",
    "Haskell": "#5e5086",
    "Haxe": "#df7900",
    "HCL": None,
    "HiveQL": "#dce200",
    "HLSL": None,
    "HTML": "#e34c26",
    "Hy": "#7790B2",
    "HyPhy": None,
    "IDL": "#a3522f",
    "Idris": "#b30000",
    "IGOR Pro": None,
    "Inform 7": None,
    "Inno Setup": None,
    "Io": "#a9188d",
    "Ioke": "#078193",
    "Isabelle": "#FEFE00",
    "Isabelle ROOT": None,
    "J": "#9EEDFF",
    "Jasmin": None,
    "Java": "#b07219",
    "Java Server Pages": None,
    "JavaScript": "#f1e05a",
    "JFlex": None,
    "Jison": None,
    "Jison Lex": None,
    "Jolie": "#843179",
    "JSONiq": "#40d47e",
    "Jsonnet": "#0064bd",
    "JSX": None,
    "Julia": "#a270ba",
    "Jupyter Notebook": "#DA5B0B",
    "Kotlin": "#F18E33",
    "KRL": "#28430A",
    "LabVIEW": None,
    "Lasso": "#999999",
    "Lean": None,
    "Lex": "#DBCA00",
    "LFE": "#4C3023",
    "LilyPond": None,
    "Limbo": None,
    "Literate Agda": None,
    "Literate CoffeeScript": None,
    "Literate Haskell": None,
    "LiveScript": "#499886",
    "LLVM": "#185619",
    "Logos": None,
    "Logtalk": None,
    "LOLCODE": "#cc9900",
    "LookML": "#652B81",
    "LoomScript": None,
    "LSL": "#3d9970",
    "Lua": "#000080",
    "M": None,
    "M4": None,
    "M4Sugar": None,
    "Makefile": "#427819",
    "Mako": None,
    "Mask": "#f97732",
    "Mathematica": None,
    "MATLAB": "#e16737",
    "Max": "#c4a79c",
    "MAXScript": "#00a6a6",
    "mcfunction": "#E22837",
    "Mercury": "#ff2b2b",
    "Meson": "#007800",
    "Metal": "#8f14e9",
    "MiniD": None,
    "Mirah": "#c7a938",
    "Modelica": None,
    "Modula-2": None,
    "Modula-3": "#223388",
    "Module Management System": None,
    "Monkey": None,
    "Moocode": None,
    "MoonScript": None,
    "MQL4": "#62A8D6",
    "MQL5": "#4A76B8",
    "MTML": "#b7e1f4",
    "MUF": None,
    "mupad": None,
    "Myghty": None,
    "NCL": "#28431f",
    "Nearley": "#990000",
    "Nemerle": "#3d3c6e",
    "nesC": "#94B0C7",
    "NetLinx": "#0aa0ff",
    "NetLinx+ERB": "#747faa",
    "NetLogo": "#ff6375",
    "NewLisp": "#87AED7",
    "Nextflow": "#3ac486",
    "Nim": "#37775b",
    "Nit": "#009917",
    "Nix": "#7e7eff",
    "NSIS": None,
    "Nu": "#c9df40",
    "NumPy": None,
    "Objective-C": "#438eff",
    "Objective-C++": "#6866fb",
    "Objective-J": "#ff0c5a",
    "OCaml": "#3be133",
    "Omgrofl": "#cabbff",
    "ooc": "#b0b77e",
    "Opa": None,
    "Opal": "#f7ede0",
    "OpenCL": None,
    "OpenEdge ABL": None,
    "OpenRC runscript": None,
    "OpenSCAD": None,
    "Ox": None,
    "Oxygene": "#cdd0e3",
    "Oz": "#fab738",
    "P4": "#7055b5",
    "Pan": "#cc0000",
    "Papyrus": "#6600cc",
    "Parrot": "#f3ca0a",
    "Parrot Assembly": None,
    "Parrot Internal Representation": None,
    "Pascal": "#E3F171",
    "Pawn": "#dbb284",
    "Pep8": "#C76F5B",
    "Perl": "#0298c3",
    "Perl 6": "#0000fb",
    "PHP": "#4F5D95",
    "PicoLisp": None,
    "PigLatin": "#fcd7de",
    "Pike": "#005390",
    "PLpgSQL": None,
    "PLSQL": "#dad8d8",
    "PogoScript": "#d80074",
    "Pony": None,
    "PostScript": "#da291c",
    "POV-Ray SDL": None,
    "PowerBuilder": "#8f0f8d",
    "PowerShell": "#012456",
    "Processing": "#0096D8",
    "Prolog": "#74283c",
    "Propeller Spin": "#7fa2a7",
    "Puppet": "#302B6D",
    "PureBasic": "#5a6986",
    "PureScript": "#1D222D",
    "Python": "#3572A5",
    "Python console": None,
    "q": "#0040cd",
    "QMake": None,
    "QML": "#44a51c",
    "Quake": "#882233",
    "R": "#198CE7",
    "Racket": "#3c5caa",
    "Ragel": "#9d5200",
    "RAML": "#77d9fb",
    "Rascal": "#fffaa0",
    "REALbasic": None,
    "Reason": None,
    "Rebol": "#358a5b",
    "Red": "#f50000",
    "Redcode": None,
    "Ren'Py": "#ff7f7f",
    "RenderScript": None,
    "REXX": None,
    "Ring": "#2D54CB",
    "RobotFramework": None,
    "Roff": "#ecdebe",
    "Rouge": "#cc0088",
    "RPC": None,
    "Ruby": "#701516",
    "RUNOFF": "#665a4e",
    "Rust": "#dea584",
    "Sage": None,
    "SaltStack": "#646464",
    "SAS": "#B34936",
    "Scala": "#c22d40",
    "Scheme": "#1e4aec",
    "Scilab": None,
    "sed": "#64b970",
    "Self": "#0579aa",
    "ShaderLab": None,
    "Shell": "#89e051",
    "ShellSession": None,
    "Shen": "#120F14",
    "Slash": "#007eff",
    "Slice": "#003fa2",
    "Smali": None,
    "Smalltalk": "#596706",
    "Smarty": None,
    "SMT": None,
    "Solidity": "#AA6746",
    "SourcePawn": "#5c7611",
    "SQF": "#3F3F3F",
    "SQLPL": None,
    "Squirrel": "#800000",
    "SRecode Template": "#348a34",
    "Stan": "#b2011d",
    "Standard ML": "#dc566d",
    "Stata": None,
    "SuperCollider": "#46390b",
    "Swift": "#ffac45",
    "SystemVerilog": "#DAE1C2",
    "Tcl": "#e4cc98",
    "Tcsh": None,
    "Terra": "#00004c",
    "TeX": "#3D6117",
    "Thrift": None,
    "TI Program": "#A0AA87",
    "TLA": None,
    "Turing": "#cf142b",
    "TXL": None,
    "TypeScript": "#2b7489",
    "Unified Parallel C": None,
    "Unix Assembly": None,
    "Uno": None,
    "UnrealScript": "#a54c4d",
    "UrWeb": None,
    "Vala": "#fbe5cd",
    "VCL": "#148AA8",
    "Verilog": "#b2b7f8",
    "VHDL": "#adb2cb",
    "Vim script": "#199f4b",
    "Visual Basic": "#945db7",
    "Volt": "#1F1F1F",
    "Vue": "#2c3e50",
    "wdl": "#42f1f4",
    "WebAssembly": "#04133b",
    "WebIDL": None,
    "wisp": "#7582D1",
    "X10": "#4B6BEF",
    "xBase": "#403a40",
    "XC": "#99DA07",
    "Xojo": None,
    "XProc": None,
    "XQuery": "#5232e7",
    "XS": None,
    "XSLT": "#EB8CEB",
    "Xtend": None,
    "Yacc": "#4B6C4B",
    "YARA": "#220000",
    "YASnippet": "#32AB90",
    "ZAP": "#0d665e",
    "Zephir": "#118f9e",
    "Zig": "#ec915c",
    "ZIL": "#dc75e5",
    "Zimpl": None
}

def exists(name):
    """return True if language exits, else False"""
    for k,v in COLORS.items():
        if k.lower()==name.lower():
            return True
    return False

def get(name,default=None):
    """return a string with language color"""
    if not default:
        default = '#ccc'
    for k,v in COLORS.items():
        if k.lower()==name.lower():
            return v
    return default
