# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_PIV.ui',
# licensing of 'main_PIV.ui' applies.
#
# Created: Fri Nov 27 10:32:11 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(836, 736)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Main_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_tabs.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.Main_tabs.setFont(font)
        self.Main_tabs.setAcceptDrops(False)
        self.Main_tabs.setAccessibleDescription("")
        self.Main_tabs.setAutoFillBackground(False)
        self.Main_tabs.setStyleSheet("")
        self.Main_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Main_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Main_tabs.setElideMode(QtCore.Qt.ElideNone)
        self.Main_tabs.setUsesScrollButtons(True)
        self.Main_tabs.setDocumentMode(False)
        self.Main_tabs.setTabsClosable(False)
        self.Main_tabs.setMovable(False)
        self.Main_tabs.setTabBarAutoHide(False)
        self.Main_tabs.setObjectName("Main_tabs")
        self.Validation = QtWidgets.QWidget()
        self.Validation.setEnabled(True)
        self.Validation.setObjectName("Validation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Validation)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.Validation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 10, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_GB = QtWidgets.QGroupBox(self.layoutWidget)
        self.settings_GB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_GB.sizePolicy().hasHeightForWidth())
        self.settings_GB.setSizePolicy(sizePolicy)
        self.settings_GB.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.settings_GB.setFont(font)
        self.settings_GB.setAutoFillBackground(False)
        self.settings_GB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.settings_GB.setFlat(False)
        self.settings_GB.setCheckable(False)
        self.settings_GB.setChecked(False)
        self.settings_GB.setObjectName("settings_GB")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.settings_GB)
        self.gridLayout_5.setSpacing(9)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.global_velocity_CB = QtWidgets.QCheckBox(self.settings_GB)
        self.global_velocity_CB.setEnabled(True)
        self.global_velocity_CB.setObjectName("global_velocity_CB")
        self.gridLayout.addWidget(self.global_velocity_CB, 1, 0, 1, 1)
        self.global_uVelocity_LE = QtWidgets.QLineEdit(self.settings_GB)
        self.global_uVelocity_LE.setObjectName("global_uVelocity_LE")
        self.gridLayout.addWidget(self.global_uVelocity_LE, 1, 1, 1, 1)
        self.global_vVelocity_LE = QtWidgets.QLineEdit(self.settings_GB)
        self.global_vVelocity_LE.setObjectName("global_vVelocity_LE")
        self.gridLayout.addWidget(self.global_vVelocity_LE, 1, 2, 1, 1)
        self.local_velocity_CB = QtWidgets.QCheckBox(self.settings_GB)
        self.local_velocity_CB.setEnabled(True)
        self.local_velocity_CB.setObjectName("local_velocity_CB")
        self.gridLayout.addWidget(self.local_velocity_CB, 2, 0, 1, 1)
        self.local_velocity_LE = QtWidgets.QLineEdit(self.settings_GB)
        self.local_velocity_LE.setObjectName("local_velocity_LE")
        self.gridLayout.addWidget(self.local_velocity_LE, 2, 1, 1, 1)
        self.local_kernel_LE = QtWidgets.QLineEdit(self.settings_GB)
        self.local_kernel_LE.setObjectName("local_kernel_LE")
        self.gridLayout.addWidget(self.local_kernel_LE, 2, 2, 1, 1)
        self.s2n_CB = QtWidgets.QCheckBox(self.settings_GB)
        self.s2n_CB.setEnabled(True)
        self.s2n_CB.setObjectName("s2n_CB")
        self.gridLayout.addWidget(self.s2n_CB, 0, 0, 1, 1)
        self.global_std_CB = QtWidgets.QCheckBox(self.settings_GB)
        self.global_std_CB.setEnabled(True)
        self.global_std_CB.setObjectName("global_std_CB")
        self.gridLayout.addWidget(self.global_std_CB, 3, 0, 1, 2)
        self.s2n_LE = QtWidgets.QLineEdit(self.settings_GB)
        self.s2n_LE.setEnabled(True)
        self.s2n_LE.setText("")
        self.s2n_LE.setFrame(True)
        self.s2n_LE.setObjectName("s2n_LE")
        self.gridLayout.addWidget(self.s2n_LE, 0, 2, 1, 1)
        self.global_std_LE = QtWidgets.QLineEdit(self.settings_GB)
        self.global_std_LE.setObjectName("global_std_LE")
        self.gridLayout.addWidget(self.global_std_LE, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_settings_PB = QtWidgets.QPushButton(self.settings_GB)
        self.apply_settings_PB.setObjectName("apply_settings_PB")
        self.horizontalLayout.addWidget(self.apply_settings_PB)
        self.load_settings_PB = QtWidgets.QPushButton(self.settings_GB)
        self.load_settings_PB.setObjectName("load_settings_PB")
        self.horizontalLayout.addWidget(self.load_settings_PB)
        self.save_settings_PB = QtWidgets.QPushButton(self.settings_GB)
        self.save_settings_PB.setEnabled(True)
        self.save_settings_PB.setObjectName("save_settings_PB")
        self.horizontalLayout.addWidget(self.save_settings_PB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.settings_GB)
        self.files_TW = QtWidgets.QTreeWidget(self.layoutWidget)
        self.files_TW.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.files_TW.sizePolicy().hasHeightForWidth())
        self.files_TW.setSizePolicy(sizePolicy)
        self.files_TW.setMinimumSize(QtCore.QSize(0, 0))
        self.files_TW.setAutoScroll(True)
        self.files_TW.setIndentation(0)
        self.files_TW.setItemsExpandable(True)
        self.files_TW.setAnimated(True)
        self.files_TW.setAllColumnsShowFocus(False)
        self.files_TW.setWordWrap(False)
        self.files_TW.setHeaderHidden(False)
        self.files_TW.setObjectName("files_TW")
        self.files_TW.header().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.files_TW)
        self.plot_widget = QtWidgets.QWidget(self.splitter)
        self.plot_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setMinimumSize(QtCore.QSize(450, 0))
        self.plot_widget.setAutoFillBackground(False)
        self.plot_widget.setObjectName("plot_widget")
        self.plot_settings_LE = QtWidgets.QLineEdit(self.plot_widget)
        self.plot_settings_LE.setGeometry(QtCore.QRect(160, 30, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_settings_LE.sizePolicy().hasHeightForWidth())
        self.plot_settings_LE.setSizePolicy(sizePolicy)
        self.plot_settings_LE.setMinimumSize(QtCore.QSize(70, 0))
        self.plot_settings_LE.setMaximumSize(QtCore.QSize(70, 16777215))
        self.plot_settings_LE.setObjectName("plot_settings_LE")
        self.BV_settings_CB = QtWidgets.QComboBox(self.plot_widget)
        self.BV_settings_CB.setGeometry(QtCore.QRect(240, 30, 165, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BV_settings_CB.sizePolicy().hasHeightForWidth())
        self.BV_settings_CB.setSizePolicy(sizePolicy)
        self.BV_settings_CB.setMinimumSize(QtCore.QSize(165, 30))
        self.BV_settings_CB.setMaximumSize(QtCore.QSize(165, 16777215))
        self.BV_settings_CB.setObjectName("BV_settings_CB")
        self.BV_settings_CB.addItem("")
        self.BV_settings_CB.addItem("")
        self.BV_settings_CB.addItem("")
        self.BV_settings_CB.addItem("")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.Main_tabs.addTab(self.Validation, "")
        self.Process = QtWidgets.QWidget()
        self.Process.setObjectName("Process")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Process)
        self.gridLayout_12.setContentsMargins(5, 10, 5, 0)
        self.gridLayout_12.setVerticalSpacing(9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_11 = QtWidgets.QGroupBox(self.Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_25.setContentsMargins(10, 10, 10, 15)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setHorizontalSpacing(15)
        self.gridLayout_26.setVerticalSpacing(12)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        self.label_21.setObjectName("label_21")
        self.gridLayout_26.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_11)
        self.label_22.setObjectName("label_22")
        self.gridLayout_26.addWidget(self.label_22, 1, 0, 1, 1)
        self.run_start_PB = QtWidgets.QPushButton(self.groupBox_11)
        self.run_start_PB.setEnabled(True)
        self.run_start_PB.setStyleSheet("")
        self.run_start_PB.setObjectName("run_start_PB")
        self.gridLayout_26.addWidget(self.run_start_PB, 0, 2, 1, 1)
        self.run_stop_PB = QtWidgets.QPushButton(self.groupBox_11)
        self.run_stop_PB.setEnabled(True)
        self.run_stop_PB.setObjectName("run_stop_PB")
        self.gridLayout_26.addWidget(self.run_stop_PB, 0, 3, 1, 1)
        self.run_overalprogress_PBar = QtWidgets.QProgressBar(self.groupBox_11)
        self.run_overalprogress_PBar.setEnabled(False)
        self.run_overalprogress_PBar.setStyleSheet("")
        self.run_overalprogress_PBar.setProperty("value", 0)
        self.run_overalprogress_PBar.setTextVisible(True)
        self.run_overalprogress_PBar.setObjectName("run_overalprogress_PBar")
        self.gridLayout_26.addWidget(self.run_overalprogress_PBar, 2, 1, 1, 3)
        self.run_progress_PBar = QtWidgets.QProgressBar(self.groupBox_11)
        self.run_progress_PBar.setEnabled(False)
        self.run_progress_PBar.setStyleSheet("")
        self.run_progress_PBar.setProperty("value", 0)
        self.run_progress_PBar.setObjectName("run_progress_PBar")
        self.gridLayout_26.addWidget(self.run_progress_PBar, 1, 1, 1, 3)
        self.label_23 = QtWidgets.QLabel(self.groupBox_11)
        self.label_23.setObjectName("label_23")
        self.gridLayout_26.addWidget(self.label_23, 2, 0, 1, 1)
        self.run_progress_TE = QtWidgets.QPlainTextEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_progress_TE.sizePolicy().hasHeightForWidth())
        self.run_progress_TE.setSizePolicy(sizePolicy)
        self.run_progress_TE.setMaximumSize(QtCore.QSize(16777215, 80))
        self.run_progress_TE.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.run_progress_TE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.run_progress_TE.setMidLineWidth(3)
        self.run_progress_TE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.run_progress_TE.setTabChangesFocus(True)
        self.run_progress_TE.setUndoRedoEnabled(False)
        self.run_progress_TE.setReadOnly(True)
        self.run_progress_TE.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.run_progress_TE.setCenterOnScroll(True)
        self.run_progress_TE.setObjectName("run_progress_TE")
        self.gridLayout_26.addWidget(self.run_progress_TE, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_18.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_18.setHorizontalSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 2, 0, 1, 1)
        self.process_loadsettings_PB = QtWidgets.QPushButton(self.groupBox_7)
        self.process_loadsettings_PB.setObjectName("process_loadsettings_PB")
        self.gridLayout_18.addWidget(self.process_loadsettings_PB, 2, 1, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.groupBox_7)
        self.toolBox.setEnabled(True)
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.ExpPage = QtWidgets.QWidget()
        self.ExpPage.setGeometry(QtCore.QRect(0, 0, 394, 106))
        self.ExpPage.setObjectName("ExpPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ExpPage)
        self.gridLayout_2.setContentsMargins(8, 0, 8, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setHorizontalSpacing(10)
        self.gridLayout_13.setVerticalSpacing(8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_24 = QtWidgets.QLabel(self.ExpPage)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 0, 0, 1, 1)
        self.exp_directory_TB = QtWidgets.QToolButton(self.ExpPage)
        self.exp_directory_TB.setObjectName("exp_directory_TB")
        self.gridLayout_13.addWidget(self.exp_directory_TB, 0, 6, 1, 1)
        self.exp_experiments_LE = QtWidgets.QLineEdit(self.ExpPage)
        self.exp_experiments_LE.setText("")
        self.exp_experiments_LE.setObjectName("exp_experiments_LE")
        self.gridLayout_13.addWidget(self.exp_experiments_LE, 1, 1, 1, 6)
        self.label_14 = QtWidgets.QLabel(self.ExpPage)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 2, 0, 1, 1)
        self.exp_runs_LE = QtWidgets.QLineEdit(self.ExpPage)
        self.exp_runs_LE.setText("")
        self.exp_runs_LE.setObjectName("exp_runs_LE")
        self.gridLayout_13.addWidget(self.exp_runs_LE, 2, 1, 1, 6)
        self.label_25 = QtWidgets.QLabel(self.ExpPage)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 1, 0, 1, 1)
        self.exp_directory_LE = QtWidgets.QLineEdit(self.ExpPage)
        self.exp_directory_LE.setText("")
        self.exp_directory_LE.setObjectName("exp_directory_LE")
        self.gridLayout_13.addWidget(self.exp_directory_LE, 0, 1, 1, 5)
        self.label = QtWidgets.QLabel(self.ExpPage)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 3, 0, 1, 1)
        self.exp_patA_LE = QtWidgets.QLineEdit(self.ExpPage)
        self.exp_patA_LE.setObjectName("exp_patA_LE")
        self.gridLayout_13.addWidget(self.exp_patA_LE, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.ExpPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ExpPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 3, 4, 1, 1)
        self.exp_patB_LE = QtWidgets.QLineEdit(self.ExpPage)
        self.exp_patB_LE.setObjectName("exp_patB_LE")
        self.gridLayout_13.addWidget(self.exp_patB_LE, 3, 3, 1, 1)
        self.exp_nfiles_LE = QtWidgets.QLineEdit(self.ExpPage)
        self.exp_nfiles_LE.setObjectName("exp_nfiles_LE")
        self.gridLayout_13.addWidget(self.exp_nfiles_LE, 3, 5, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.toolBox.addItem(self.ExpPage, "")
        self.PrePage = QtWidgets.QWidget()
        self.PrePage.setGeometry(QtCore.QRect(0, 0, 316, 75))
        self.PrePage.setObjectName("PrePage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PrePage)
        self.gridLayout_3.setContentsMargins(8, 0, 8, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(10)
        self.gridLayout_7.setVerticalSpacing(8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pre_background_CB = QtWidgets.QCheckBox(self.PrePage)
        self.pre_background_CB.setObjectName("pre_background_CB")
        self.gridLayout_7.addWidget(self.pre_background_CB, 0, 0, 1, 1)
        self.pre_staticmask_CB = QtWidgets.QCheckBox(self.PrePage)
        self.pre_staticmask_CB.setObjectName("pre_staticmask_CB")
        self.gridLayout_7.addWidget(self.pre_staticmask_CB, 1, 0, 1, 1)
        self.pre_sm_path_TB = QtWidgets.QToolButton(self.PrePage)
        self.pre_sm_path_TB.setObjectName("pre_sm_path_TB")
        self.gridLayout_7.addWidget(self.pre_sm_path_TB, 1, 4, 1, 1)
        self.pre_dynamicmask_CB = QtWidgets.QCheckBox(self.PrePage)
        self.pre_dynamicmask_CB.setObjectName("pre_dynamicmask_CB")
        self.gridLayout_7.addWidget(self.pre_dynamicmask_CB, 2, 0, 1, 3)
        self.pre_sm_path_LE = QtWidgets.QLineEdit(self.PrePage)
        self.pre_sm_path_LE.setObjectName("pre_sm_path_LE")
        self.gridLayout_7.addWidget(self.pre_sm_path_LE, 1, 1, 1, 3)
        self.pre_bg_nfiles_LE = QtWidgets.QLineEdit(self.PrePage)
        self.pre_bg_nfiles_LE.setObjectName("pre_bg_nfiles_LE")
        self.gridLayout_7.addWidget(self.pre_bg_nfiles_LE, 0, 1, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.toolBox.addItem(self.PrePage, "")
        self.ProPage = QtWidgets.QWidget()
        self.ProPage.setGeometry(QtCore.QRect(0, 0, 473, 78))
        self.ProPage.setObjectName("ProPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ProPage)
        self.gridLayout_8.setContentsMargins(8, 0, 8, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setHorizontalSpacing(10)
        self.gridLayout_9.setVerticalSpacing(8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pro_scale_LE = QtWidgets.QLineEdit(self.ProPage)
        self.pro_scale_LE.setText("")
        self.pro_scale_LE.setPlaceholderText("")
        self.pro_scale_LE.setObjectName("pro_scale_LE")
        self.gridLayout_9.addWidget(self.pro_scale_LE, 1, 6, 1, 1)
        self.pro_searcharea_LE = QtWidgets.QLineEdit(self.ProPage)
        self.pro_searcharea_LE.setText("")
        self.pro_searcharea_LE.setPlaceholderText("")
        self.pro_searcharea_LE.setObjectName("pro_searcharea_LE")
        self.gridLayout_9.addWidget(self.pro_searcharea_LE, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ProPage)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 2, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.ProPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ProPage)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ProPage)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 1, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ProPage)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 0, 1, 2)
        self.pro_sig2noise_CB = QtWidgets.QComboBox(self.ProPage)
        self.pro_sig2noise_CB.setObjectName("pro_sig2noise_CB")
        self.pro_sig2noise_CB.addItem("")
        self.pro_sig2noise_CB.addItem("")
        self.pro_sig2noise_CB.addItem("")
        self.gridLayout_9.addWidget(self.pro_sig2noise_CB, 1, 2, 1, 1)
        self.pro_timestep_LE = QtWidgets.QLineEdit(self.ProPage)
        self.pro_timestep_LE.setText("")
        self.pro_timestep_LE.setPlaceholderText("")
        self.pro_timestep_LE.setObjectName("pro_timestep_LE")
        self.gridLayout_9.addWidget(self.pro_timestep_LE, 1, 4, 1, 1)
        self.pro_ncpus_LE = QtWidgets.QLineEdit(self.ProPage)
        self.pro_ncpus_LE.setText("")
        self.pro_ncpus_LE.setPlaceholderText("")
        self.pro_ncpus_LE.setObjectName("pro_ncpus_LE")
        self.gridLayout_9.addWidget(self.pro_ncpus_LE, 2, 2, 1, 1)
        self.pro_overlap_LE = QtWidgets.QLineEdit(self.ProPage)
        self.pro_overlap_LE.setText("")
        self.pro_overlap_LE.setPlaceholderText("")
        self.pro_overlap_LE.setObjectName("pro_overlap_LE")
        self.gridLayout_9.addWidget(self.pro_overlap_LE, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ProPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ProPage)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 0, 1, 2)
        self.pro_windowsize_LE = QtWidgets.QLineEdit(self.ProPage)
        self.pro_windowsize_LE.setText("")
        self.pro_windowsize_LE.setPlaceholderText("")
        self.pro_windowsize_LE.setObjectName("pro_windowsize_LE")
        self.gridLayout_9.addWidget(self.pro_windowsize_LE, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.toolBox.addItem(self.ProPage, "")
        self.PosPage = QtWidgets.QWidget()
        self.PosPage.setGeometry(QtCore.QRect(0, 0, 439, 246))
        self.PosPage.setObjectName("PosPage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.PosPage)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_9 = QtWidgets.QGroupBox(self.PosPage)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_21.setContentsMargins(8, 10, 8, 5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.pos_std_LE = QtWidgets.QLineEdit(self.groupBox_9)
        self.pos_std_LE.setObjectName("pos_std_LE")
        self.gridLayout_22.addWidget(self.pos_std_LE, 1, 1, 1, 1)
        self.pos_s2n_ratio_LE = QtWidgets.QLineEdit(self.groupBox_9)
        self.pos_s2n_ratio_LE.setEnabled(True)
        self.pos_s2n_ratio_LE.setText("")
        self.pos_s2n_ratio_LE.setFrame(True)
        self.pos_s2n_ratio_LE.setObjectName("pos_s2n_ratio_LE")
        self.gridLayout_22.addWidget(self.pos_s2n_ratio_LE, 0, 1, 1, 1)
        self.pos_gv_ulim_LE = QtWidgets.QLineEdit(self.groupBox_9)
        self.pos_gv_ulim_LE.setObjectName("pos_gv_ulim_LE")
        self.gridLayout_22.addWidget(self.pos_gv_ulim_LE, 0, 3, 1, 1)
        self.pos_std_CB = QtWidgets.QCheckBox(self.groupBox_9)
        self.pos_std_CB.setEnabled(True)
        self.pos_std_CB.setObjectName("pos_std_CB")
        self.gridLayout_22.addWidget(self.pos_std_CB, 1, 0, 1, 1)
        self.pos_localvelocity_CB = QtWidgets.QCheckBox(self.groupBox_9)
        self.pos_localvelocity_CB.setEnabled(True)
        self.pos_localvelocity_CB.setObjectName("pos_localvelocity_CB")
        self.gridLayout_22.addWidget(self.pos_localvelocity_CB, 1, 2, 1, 1)
        self.pos_lv_uvdiff_LE = QtWidgets.QLineEdit(self.groupBox_9)
        self.pos_lv_uvdiff_LE.setObjectName("pos_lv_uvdiff_LE")
        self.gridLayout_22.addWidget(self.pos_lv_uvdiff_LE, 1, 3, 1, 1)
        self.pos_sig2noise_CB = QtWidgets.QCheckBox(self.groupBox_9)
        self.pos_sig2noise_CB.setEnabled(True)
        self.pos_sig2noise_CB.setObjectName("pos_sig2noise_CB")
        self.gridLayout_22.addWidget(self.pos_sig2noise_CB, 0, 0, 1, 1)
        self.pos_globalvelocity_CB = QtWidgets.QCheckBox(self.groupBox_9)
        self.pos_globalvelocity_CB.setEnabled(True)
        self.pos_globalvelocity_CB.setObjectName("pos_globalvelocity_CB")
        self.gridLayout_22.addWidget(self.pos_globalvelocity_CB, 0, 2, 1, 1)
        self.pos_lv_kernel_LE = QtWidgets.QLineEdit(self.groupBox_9)
        self.pos_lv_kernel_LE.setObjectName("pos_lv_kernel_LE")
        self.gridLayout_22.addWidget(self.pos_lv_kernel_LE, 1, 4, 1, 1)
        self.pos_gv_vlim_LE = QtWidgets.QLineEdit(self.groupBox_9)
        self.pos_gv_vlim_LE.setObjectName("pos_gv_vlim_LE")
        self.gridLayout_22.addWidget(self.pos_gv_vlim_LE, 0, 4, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.PosPage)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_14.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pos_badvector_CB = QtWidgets.QCheckBox(self.groupBox_10)
        self.pos_badvector_CB.setEnabled(True)
        self.pos_badvector_CB.setObjectName("pos_badvector_CB")
        self.gridLayout_6.addWidget(self.pos_badvector_CB, 0, 0, 1, 2)
        self.pos_bv_niterations_LE = QtWidgets.QLineEdit(self.groupBox_10)
        self.pos_bv_niterations_LE.setObjectName("pos_bv_niterations_LE")
        self.gridLayout_6.addWidget(self.pos_bv_niterations_LE, 0, 3, 1, 1)
        self.pos_bv_method_CB = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_bv_method_CB.sizePolicy().hasHeightForWidth())
        self.pos_bv_method_CB.setSizePolicy(sizePolicy)
        self.pos_bv_method_CB.setObjectName("pos_bv_method_CB")
        self.pos_bv_method_CB.addItem("")
        self.pos_bv_method_CB.addItem("")
        self.pos_bv_method_CB.addItem("")
        self.gridLayout_6.addWidget(self.pos_bv_method_CB, 0, 2, 1, 1)
        self.pos_bv_kernel_LE = QtWidgets.QLineEdit(self.groupBox_10)
        self.pos_bv_kernel_LE.setObjectName("pos_bv_kernel_LE")
        self.gridLayout_6.addWidget(self.pos_bv_kernel_LE, 0, 4, 1, 1)
        self.pos_smth_factor_LE = QtWidgets.QLineEdit(self.groupBox_10)
        self.pos_smth_factor_LE.setObjectName("pos_smth_factor_LE")
        self.gridLayout_6.addWidget(self.pos_smth_factor_LE, 1, 2, 1, 1)
        self.pos_smoothing_CB = QtWidgets.QCheckBox(self.groupBox_10)
        self.pos_smoothing_CB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_smoothing_CB.sizePolicy().hasHeightForWidth())
        self.pos_smoothing_CB.setSizePolicy(sizePolicy)
        self.pos_smoothing_CB.setObjectName("pos_smoothing_CB")
        self.gridLayout_6.addWidget(self.pos_smoothing_CB, 1, 0, 1, 2)
        self.pos_fm_LE = QtWidgets.QLineEdit(self.groupBox_10)
        self.pos_fm_LE.setObjectName("pos_fm_LE")
        self.gridLayout_6.addWidget(self.pos_fm_LE, 2, 2, 1, 1)
        self.pos_fieldmanip_CB = QtWidgets.QCheckBox(self.groupBox_10)
        self.pos_fieldmanip_CB.setEnabled(True)
        self.pos_fieldmanip_CB.setObjectName("pos_fieldmanip_CB")
        self.gridLayout_6.addWidget(self.pos_fieldmanip_CB, 2, 0, 1, 2)
        self.gridLayout_14.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(5, 10, 25, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.PosPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(150, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.pos_output_CB = QtWidgets.QComboBox(self.PosPage)
        self.pos_output_CB.setObjectName("pos_output_CB")
        self.pos_output_CB.addItem("")
        self.pos_output_CB.addItem("")
        self.horizontalLayout_3.addWidget(self.pos_output_CB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 2)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.toolBox.addItem(self.PosPage, "")
        self.gridLayout_18.addWidget(self.toolBox, 0, 0, 1, 3)
        self.process_savesettings_PB = QtWidgets.QPushButton(self.groupBox_7)
        self.process_savesettings_PB.setObjectName("process_savesettings_PB")
        self.gridLayout_18.addWidget(self.process_savesettings_PB, 2, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.Main_tabs.addTab(self.Process, "")
        self.FrequencyAnalysis = QtWidgets.QWidget()
        self.FrequencyAnalysis.setObjectName("FrequencyAnalysis")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FrequencyAnalysis)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.freq_exp_GB = QtWidgets.QGroupBox(self.FrequencyAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.freq_exp_GB.sizePolicy().hasHeightForWidth())
        self.freq_exp_GB.setSizePolicy(sizePolicy)
        self.freq_exp_GB.setObjectName("freq_exp_GB")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.freq_exp_GB)
        self.gridLayout_23.setHorizontalSpacing(20)
        self.gridLayout_23.setVerticalSpacing(5)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_30 = QtWidgets.QLabel(self.freq_exp_GB)
        self.label_30.setObjectName("label_30")
        self.gridLayout_23.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.freq_exp_GB)
        self.label_31.setObjectName("label_31")
        self.gridLayout_23.addWidget(self.label_31, 2, 0, 1, 1)
        self.freq_exp_LE = QtWidgets.QLineEdit(self.freq_exp_GB)
        self.freq_exp_LE.setText("")
        self.freq_exp_LE.setObjectName("freq_exp_LE")
        self.gridLayout_23.addWidget(self.freq_exp_LE, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.freq_exp_GB)
        self.label_32.setObjectName("label_32")
        self.gridLayout_23.addWidget(self.label_32, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.freq_exp_GB)
        self.label_13.setObjectName("label_13")
        self.gridLayout_23.addWidget(self.label_13, 3, 0, 1, 1)
        self.freq_pat_LE = QtWidgets.QLineEdit(self.freq_exp_GB)
        self.freq_pat_LE.setObjectName("freq_pat_LE")
        self.gridLayout_23.addWidget(self.freq_pat_LE, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.freq_exp_GB)
        self.label_33.setObjectName("label_33")
        self.gridLayout_23.addWidget(self.label_33, 3, 2, 1, 1)
        self.freq_dir_LE = QtWidgets.QLineEdit(self.freq_exp_GB)
        self.freq_dir_LE.setText("")
        self.freq_dir_LE.setObjectName("freq_dir_LE")
        self.gridLayout_23.addWidget(self.freq_dir_LE, 1, 1, 1, 1)
        self.freq_dir_TB = QtWidgets.QToolButton(self.freq_exp_GB)
        self.freq_dir_TB.setObjectName("freq_dir_TB")
        self.gridLayout_23.addWidget(self.freq_dir_TB, 1, 2, 1, 1)
        self.freq_nf_LE = QtWidgets.QLineEdit(self.freq_exp_GB)
        self.freq_nf_LE.setObjectName("freq_nf_LE")
        self.gridLayout_23.addWidget(self.freq_nf_LE, 3, 3, 1, 1)
        self.freq_run_LE = QtWidgets.QLineEdit(self.freq_exp_GB)
        self.freq_run_LE.setText("")
        self.freq_run_LE.setObjectName("freq_run_LE")
        self.gridLayout_23.addWidget(self.freq_run_LE, 2, 3, 1, 1)
        self.freq_load_from_PB = QtWidgets.QPushButton(self.freq_exp_GB)
        self.freq_load_from_PB.setObjectName("freq_load_from_PB")
        self.gridLayout_23.addWidget(self.freq_load_from_PB, 0, 0, 1, 4)
        self.verticalLayout_3.addWidget(self.freq_exp_GB)
        self.freq_analysis_GB = QtWidgets.QGroupBox(self.FrequencyAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.freq_analysis_GB.sizePolicy().hasHeightForWidth())
        self.freq_analysis_GB.setSizePolicy(sizePolicy)
        self.freq_analysis_GB.setObjectName("freq_analysis_GB")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.freq_analysis_GB)
        self.gridLayout_29.setContentsMargins(-1, -1, -1, 2)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.label_36 = QtWidgets.QLabel(self.freq_analysis_GB)
        self.label_36.setObjectName("label_36")
        self.gridLayout_29.addWidget(self.label_36, 0, 0, 1, 1)
        self.freq_fs_LE = QtWidgets.QLineEdit(self.freq_analysis_GB)
        self.freq_fs_LE.setObjectName("freq_fs_LE")
        self.gridLayout_29.addWidget(self.freq_fs_LE, 0, 1, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.freq_analysis_GB)
        self.label_37.setObjectName("label_37")
        self.gridLayout_29.addWidget(self.label_37, 0, 3, 1, 1)
        self.freq_dim_LE = QtWidgets.QLineEdit(self.freq_analysis_GB)
        self.freq_dim_LE.setObjectName("freq_dim_LE")
        self.gridLayout_29.addWidget(self.freq_dim_LE, 0, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.freq_analysis_GB)
        self.label_38.setObjectName("label_38")
        self.gridLayout_29.addWidget(self.label_38, 0, 5, 1, 1)
        self.freq_flim_LE = QtWidgets.QLineEdit(self.freq_analysis_GB)
        self.freq_flim_LE.setText("")
        self.freq_flim_LE.setObjectName("freq_flim_LE")
        self.gridLayout_29.addWidget(self.freq_flim_LE, 0, 6, 1, 1)
        self.freq_pt_fft_CB = QtWidgets.QCheckBox(self.freq_analysis_GB)
        self.freq_pt_fft_CB.setObjectName("freq_pt_fft_CB")
        self.gridLayout_29.addWidget(self.freq_pt_fft_CB, 1, 0, 1, 1)
        self.freq_pt_stft_CB = QtWidgets.QCheckBox(self.freq_analysis_GB)
        self.freq_pt_stft_CB.setObjectName("freq_pt_stft_CB")
        self.gridLayout_29.addWidget(self.freq_pt_stft_CB, 2, 0, 1, 1)
        self.freq_gb_fft_CB = QtWidgets.QCheckBox(self.freq_analysis_GB)
        self.freq_gb_fft_CB.setObjectName("freq_gb_fft_CB")
        self.gridLayout_29.addWidget(self.freq_gb_fft_CB, 3, 0, 1, 1)
        self.freq_gb_stft_CB = QtWidgets.QCheckBox(self.freq_analysis_GB)
        self.freq_gb_stft_CB.setObjectName("freq_gb_stft_CB")
        self.gridLayout_29.addWidget(self.freq_gb_stft_CB, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.freq_analysis_GB)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_31.setContentsMargins(-1, 10, -1, 2)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_39 = QtWidgets.QLabel(self.groupBox_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_31.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_31.addWidget(self.label_40, 0, 2, 1, 1)
        self.freq_noverlap_LE = QtWidgets.QLineEdit(self.groupBox_3)
        self.freq_noverlap_LE.setObjectName("freq_noverlap_LE")
        self.gridLayout_31.addWidget(self.freq_noverlap_LE, 0, 3, 1, 1)
        self.freq_nperseg_LE = QtWidgets.QLineEdit(self.groupBox_3)
        self.freq_nperseg_LE.setObjectName("freq_nperseg_LE")
        self.gridLayout_31.addWidget(self.freq_nperseg_LE, 0, 1, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_3, 3, 1, 2, 6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.freq_analysis_GB)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_30.setContentsMargins(-1, 10, -1, 2)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.gridLayout_30.addWidget(self.label_41, 0, 0, 1, 1)
        self.freq_pt_loc_CB = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_pt_loc_CB.sizePolicy().hasHeightForWidth())
        self.freq_pt_loc_CB.setSizePolicy(sizePolicy)
        self.freq_pt_loc_CB.setObjectName("freq_pt_loc_CB")
        self.freq_pt_loc_CB.addItem("")
        self.freq_pt_loc_CB.addItem("")
        self.freq_pt_loc_CB.addItem("")
        self.gridLayout_30.addWidget(self.freq_pt_loc_CB, 0, 1, 1, 1)
        self.freq_pt_loc_LE = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_pt_loc_LE.sizePolicy().hasHeightForWidth())
        self.freq_pt_loc_LE.setSizePolicy(sizePolicy)
        self.freq_pt_loc_LE.setObjectName("freq_pt_loc_LE")
        self.gridLayout_30.addWidget(self.freq_pt_loc_LE, 0, 2, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_2, 1, 1, 2, 6)
        self.verticalLayout_3.addWidget(self.freq_analysis_GB)
        self.frame = QtWidgets.QFrame(self.FrequencyAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        spacerItem2 = QtWidgets.QSpacerItem(590, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem2, 0, 0, 1, 1)
        self.freq_load_PB = QtWidgets.QPushButton(self.frame)
        self.freq_load_PB.setObjectName("freq_load_PB")
        self.gridLayout_32.addWidget(self.freq_load_PB, 0, 1, 1, 1)
        self.freq_save_PB = QtWidgets.QPushButton(self.frame)
        self.freq_save_PB.setObjectName("freq_save_PB")
        self.gridLayout_32.addWidget(self.freq_save_PB, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.freq_run_GB = QtWidgets.QGroupBox(self.FrequencyAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.freq_run_GB.sizePolicy().hasHeightForWidth())
        self.freq_run_GB.setSizePolicy(sizePolicy)
        self.freq_run_GB.setObjectName("freq_run_GB")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.freq_run_GB)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setHorizontalSpacing(15)
        self.gridLayout_28.setVerticalSpacing(12)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_34 = QtWidgets.QLabel(self.freq_run_GB)
        self.label_34.setObjectName("label_34")
        self.gridLayout_28.addWidget(self.label_34, 1, 0, 1, 1)
        self.freq_start_PB = QtWidgets.QPushButton(self.freq_run_GB)
        self.freq_start_PB.setEnabled(True)
        self.freq_start_PB.setStyleSheet("")
        self.freq_start_PB.setObjectName("freq_start_PB")
        self.gridLayout_28.addWidget(self.freq_start_PB, 0, 2, 1, 1)
        self.freq_stop_PB = QtWidgets.QPushButton(self.freq_run_GB)
        self.freq_stop_PB.setEnabled(True)
        self.freq_stop_PB.setObjectName("freq_stop_PB")
        self.gridLayout_28.addWidget(self.freq_stop_PB, 0, 3, 1, 1)
        self.freq_progress_PBar = QtWidgets.QProgressBar(self.freq_run_GB)
        self.freq_progress_PBar.setEnabled(False)
        self.freq_progress_PBar.setStyleSheet("")
        self.freq_progress_PBar.setProperty("value", 0)
        self.freq_progress_PBar.setObjectName("freq_progress_PBar")
        self.gridLayout_28.addWidget(self.freq_progress_PBar, 1, 1, 1, 3)
        self.label_35 = QtWidgets.QLabel(self.freq_run_GB)
        self.label_35.setObjectName("label_35")
        self.gridLayout_28.addWidget(self.label_35, 0, 0, 1, 1)
        self.freq_progress_TE = QtWidgets.QPlainTextEdit(self.freq_run_GB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_progress_TE.sizePolicy().hasHeightForWidth())
        self.freq_progress_TE.setSizePolicy(sizePolicy)
        self.freq_progress_TE.setMaximumSize(QtCore.QSize(16777215, 80))
        self.freq_progress_TE.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.freq_progress_TE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.freq_progress_TE.setMidLineWidth(3)
        self.freq_progress_TE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.freq_progress_TE.setTabChangesFocus(True)
        self.freq_progress_TE.setUndoRedoEnabled(False)
        self.freq_progress_TE.setReadOnly(True)
        self.freq_progress_TE.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.freq_progress_TE.setCenterOnScroll(True)
        self.freq_progress_TE.setObjectName("freq_progress_TE")
        self.gridLayout_28.addWidget(self.freq_progress_TE, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.freq_run_GB)
        self.Main_tabs.addTab(self.FrequencyAnalysis, "")
        self.ModalAnalysis = QtWidgets.QWidget()
        self.ModalAnalysis.setObjectName("ModalAnalysis")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.ModalAnalysis)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 2, 0, 1, 1)
        self.mdl_save_PB = QtWidgets.QPushButton(self.ModalAnalysis)
        self.mdl_save_PB.setObjectName("mdl_save_PB")
        self.gridLayout_15.addWidget(self.mdl_save_PB, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modal_ana_GB = QtWidgets.QGroupBox(self.ModalAnalysis)
        self.modal_ana_GB.setObjectName("modal_ana_GB")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.modal_ana_GB)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.mdl_nm_LE = QtWidgets.QLineEdit(self.modal_ana_GB)
        self.mdl_nm_LE.setObjectName("mdl_nm_LE")
        self.gridLayout_19.addWidget(self.mdl_nm_LE, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.modal_ana_GB)
        self.label_5.setObjectName("label_5")
        self.gridLayout_19.addWidget(self.label_5, 1, 0, 1, 1)
        self.mdl_method_CB = QtWidgets.QComboBox(self.modal_ana_GB)
        self.mdl_method_CB.setObjectName("mdl_method_CB")
        self.mdl_method_CB.addItem("")
        self.mdl_method_CB.addItem("")
        self.gridLayout_19.addWidget(self.mdl_method_CB, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.modal_ana_GB)
        self.label_18.setObjectName("label_18")
        self.gridLayout_19.addWidget(self.label_18, 2, 0, 1, 1)
        self.mdl_st_CB = QtWidgets.QCheckBox(self.modal_ana_GB)
        self.mdl_st_CB.setObjectName("mdl_st_CB")
        self.gridLayout_19.addWidget(self.mdl_st_CB, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.modal_ana_GB)
        self.modal_rec_GB = QtWidgets.QGroupBox(self.ModalAnalysis)
        self.modal_rec_GB.setObjectName("modal_rec_GB")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.modal_rec_GB)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.mdl_rec_CB = QtWidgets.QCheckBox(self.modal_rec_GB)
        self.mdl_rec_CB.setObjectName("mdl_rec_CB")
        self.gridLayout_17.addWidget(self.mdl_rec_CB, 0, 0, 1, 3)
        self.label_19 = QtWidgets.QLabel(self.modal_rec_GB)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.modal_rec_GB)
        self.label_20.setObjectName("label_20")
        self.gridLayout_17.addWidget(self.label_20, 2, 0, 1, 2)
        self.mdl_rec_ns_LE = QtWidgets.QLineEdit(self.modal_rec_GB)
        self.mdl_rec_ns_LE.setObjectName("mdl_rec_ns_LE")
        self.gridLayout_17.addWidget(self.mdl_rec_ns_LE, 2, 2, 1, 1)
        self.mdl_rec_nm_LE = QtWidgets.QLineEdit(self.modal_rec_GB)
        self.mdl_rec_nm_LE.setObjectName("mdl_rec_nm_LE")
        self.gridLayout_17.addWidget(self.mdl_rec_nm_LE, 1, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.modal_rec_GB)
        self.gridLayout_15.addLayout(self.horizontalLayout_2, 1, 0, 1, 4)
        self.modal_run_GB = QtWidgets.QGroupBox(self.ModalAnalysis)
        self.modal_run_GB.setObjectName("modal_run_GB")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.modal_run_GB)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setHorizontalSpacing(15)
        self.gridLayout_27.setVerticalSpacing(12)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_29 = QtWidgets.QLabel(self.modal_run_GB)
        self.label_29.setObjectName("label_29")
        self.gridLayout_27.addWidget(self.label_29, 1, 0, 1, 1)
        self.mdl_start_PB = QtWidgets.QPushButton(self.modal_run_GB)
        self.mdl_start_PB.setEnabled(True)
        self.mdl_start_PB.setStyleSheet("")
        self.mdl_start_PB.setObjectName("mdl_start_PB")
        self.gridLayout_27.addWidget(self.mdl_start_PB, 0, 2, 1, 1)
        self.mdl_stop_PB = QtWidgets.QPushButton(self.modal_run_GB)
        self.mdl_stop_PB.setEnabled(True)
        self.mdl_stop_PB.setObjectName("mdl_stop_PB")
        self.gridLayout_27.addWidget(self.mdl_stop_PB, 0, 3, 1, 1)
        self.mdl_progress_PBar = QtWidgets.QProgressBar(self.modal_run_GB)
        self.mdl_progress_PBar.setEnabled(False)
        self.mdl_progress_PBar.setStyleSheet("")
        self.mdl_progress_PBar.setProperty("value", 0)
        self.mdl_progress_PBar.setObjectName("mdl_progress_PBar")
        self.gridLayout_27.addWidget(self.mdl_progress_PBar, 1, 1, 1, 3)
        self.label_28 = QtWidgets.QLabel(self.modal_run_GB)
        self.label_28.setObjectName("label_28")
        self.gridLayout_27.addWidget(self.label_28, 0, 0, 1, 1)
        self.mdl_progress_TE = QtWidgets.QPlainTextEdit(self.modal_run_GB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdl_progress_TE.sizePolicy().hasHeightForWidth())
        self.mdl_progress_TE.setSizePolicy(sizePolicy)
        self.mdl_progress_TE.setMaximumSize(QtCore.QSize(16777215, 80))
        self.mdl_progress_TE.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mdl_progress_TE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mdl_progress_TE.setMidLineWidth(3)
        self.mdl_progress_TE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdl_progress_TE.setTabChangesFocus(True)
        self.mdl_progress_TE.setUndoRedoEnabled(False)
        self.mdl_progress_TE.setReadOnly(True)
        self.mdl_progress_TE.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.mdl_progress_TE.setCenterOnScroll(True)
        self.mdl_progress_TE.setObjectName("mdl_progress_TE")
        self.gridLayout_27.addWidget(self.mdl_progress_TE, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.modal_run_GB, 3, 0, 1, 4)
        self.modal_exp_GB = QtWidgets.QGroupBox(self.ModalAnalysis)
        self.modal_exp_GB.setObjectName("modal_exp_GB")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.modal_exp_GB)
        self.gridLayout_16.setHorizontalSpacing(20)
        self.gridLayout_16.setVerticalSpacing(5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_26 = QtWidgets.QLabel(self.modal_exp_GB)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.modal_exp_GB)
        self.label_27.setObjectName("label_27")
        self.gridLayout_16.addWidget(self.label_27, 2, 0, 1, 1)
        self.mdl_exp_LE = QtWidgets.QLineEdit(self.modal_exp_GB)
        self.mdl_exp_LE.setText("")
        self.mdl_exp_LE.setObjectName("mdl_exp_LE")
        self.gridLayout_16.addWidget(self.mdl_exp_LE, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.modal_exp_GB)
        self.label_16.setObjectName("label_16")
        self.gridLayout_16.addWidget(self.label_16, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.modal_exp_GB)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 3, 0, 1, 1)
        self.mdl_pat_LE = QtWidgets.QLineEdit(self.modal_exp_GB)
        self.mdl_pat_LE.setObjectName("mdl_pat_LE")
        self.gridLayout_16.addWidget(self.mdl_pat_LE, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.modal_exp_GB)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 3, 2, 1, 1)
        self.mdl_dir_LE = QtWidgets.QLineEdit(self.modal_exp_GB)
        self.mdl_dir_LE.setText("")
        self.mdl_dir_LE.setObjectName("mdl_dir_LE")
        self.gridLayout_16.addWidget(self.mdl_dir_LE, 1, 1, 1, 1)
        self.mdl_dir_TB = QtWidgets.QToolButton(self.modal_exp_GB)
        self.mdl_dir_TB.setObjectName("mdl_dir_TB")
        self.gridLayout_16.addWidget(self.mdl_dir_TB, 1, 2, 1, 1)
        self.mdl_nf_LE = QtWidgets.QLineEdit(self.modal_exp_GB)
        self.mdl_nf_LE.setObjectName("mdl_nf_LE")
        self.gridLayout_16.addWidget(self.mdl_nf_LE, 3, 3, 1, 1)
        self.mdl_run_LE = QtWidgets.QLineEdit(self.modal_exp_GB)
        self.mdl_run_LE.setText("")
        self.mdl_run_LE.setObjectName("mdl_run_LE")
        self.gridLayout_16.addWidget(self.mdl_run_LE, 2, 3, 1, 1)
        self.mdl_load_from_PB = QtWidgets.QPushButton(self.modal_exp_GB)
        self.mdl_load_from_PB.setObjectName("mdl_load_from_PB")
        self.gridLayout_16.addWidget(self.mdl_load_from_PB, 0, 0, 1, 4)
        self.gridLayout_15.addWidget(self.modal_exp_GB, 0, 0, 1, 4)
        self.mdl_load_PB = QtWidgets.QPushButton(self.ModalAnalysis)
        self.mdl_load_PB.setObjectName("mdl_load_PB")
        self.gridLayout_15.addWidget(self.mdl_load_PB, 2, 1, 1, 1)
        self.Main_tabs.addTab(self.ModalAnalysis, "")
        self.gridLayout_11.addWidget(self.Main_tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad_Files = QtWidgets.QAction(MainWindow)
        self.actionLoad_Files.setObjectName("actionLoad_Files")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClear_Files = QtWidgets.QAction(MainWindow)
        self.actionClear_Files.setObjectName("actionClear_Files")
        self.actionLoad_Raw_Images = QtWidgets.QAction(MainWindow)
        self.actionLoad_Raw_Images.setObjectName("actionLoad_Raw_Images")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad_Files)
        self.menuFile.addAction(self.actionClear_Files)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Main_tabs.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.settings_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Thresholding Settings", None, -1))
        self.global_velocity_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Global Velocity", None, -1))
        self.global_uVelocity_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Umin, Umax", None, -1))
        self.global_vVelocity_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Vmin, Vmax", None, -1))
        self.local_velocity_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Local Median", None, -1))
        self.local_velocity_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Udiff, Vdiff", None, -1))
        self.local_kernel_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "kernel size", None, -1))
        self.s2n_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Signal 2 Noise", None, -1))
        self.global_std_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Global Std. Deviation", None, -1))
        self.s2n_LE.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, -1))
        self.s2n_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "signal/noise", None, -1))
        self.global_std_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "std multiplier", None, -1))
        self.apply_settings_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Apply Settings", None, -1))
        self.load_settings_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Load Settings", None, -1))
        self.save_settings_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Save Settings", None, -1))
        self.files_TW.setSortingEnabled(True)
        self.files_TW.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.files_TW.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Num. Bad Vector", None, -1))
        self.plot_settings_LE.setText(QtWidgets.QApplication.translate("MainWindow", "b,r,50,2", None, -1))
        self.plot_settings_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "b,r,50,2", None, -1))
        self.BV_settings_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Show Original BV", None, -1))
        self.BV_settings_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Show Replaced BV", None, -1))
        self.BV_settings_CB.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Do Not Show BV", None, -1))
        self.BV_settings_CB.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Only Show BV", None, -1))
        self.Main_tabs.setTabText(self.Main_tabs.indexOf(self.Validation), QtWidgets.QApplication.translate("MainWindow", "Validation", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Progress", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Run Progress", None, -1))
        self.run_start_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.run_stop_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Overal Progress", None, -1))
        self.run_progress_TE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Details of the run are shown here...", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Run Settings", None, -1))
        self.process_loadsettings_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Load Settings", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Directory", None, -1))
        self.exp_directory_TB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.exp_experiments_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "experiments naming pattern", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Runs", None, -1))
        self.exp_runs_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "runs naming pattern", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Experiments", None, -1))
        self.exp_directory_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Path to the experiment directory", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Pattern A", None, -1))
        self.exp_patA_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Pattern for frame_a", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Pattern B", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Num. of files", None, -1))
        self.exp_patB_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Pattern for frame_b", None, -1))
        self.exp_nfiles_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Number of files in each run", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ExpPage), QtWidgets.QApplication.translate("MainWindow", "Experiment", None, -1))
        self.pre_background_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Background", None, -1))
        self.pre_staticmask_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Static Mask (still under development)", None, -1))
        self.pre_sm_path_TB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.pre_dynamicmask_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Dynamic Mask (still under development)", None, -1))
        self.pre_sm_path_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Path to the mask image", None, -1))
        self.pre_bg_nfiles_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Number of files to consider", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PrePage), QtWidgets.QApplication.translate("MainWindow", "Pre-Process", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Numb. CPU Cores", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Overlap", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Time Step", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Scale", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Signal/Noise Method", None, -1))
        self.pro_sig2noise_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "peak2peak", None, -1))
        self.pro_sig2noise_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "peak2mean", None, -1))
        self.pro_sig2noise_CB.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Search Area Size", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Window Size", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ProPage), QtWidgets.QApplication.translate("MainWindow", "Process", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "Validation", None, -1))
        self.pos_std_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "std multiplier", None, -1))
        self.pos_s2n_ratio_LE.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, -1))
        self.pos_s2n_ratio_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "signal/noise", None, -1))
        self.pos_gv_ulim_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Umin, Umax", None, -1))
        self.pos_std_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Global Std. Deviation", None, -1))
        self.pos_localvelocity_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Local Median", None, -1))
        self.pos_lv_uvdiff_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Udiff, Vdiff", None, -1))
        self.pos_sig2noise_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Signal 2 Noise", None, -1))
        self.pos_globalvelocity_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Global Velocity", None, -1))
        self.pos_lv_kernel_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "kernel size", None, -1))
        self.pos_gv_vlim_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Vmin, Vmax", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("MainWindow", "Vector Corrections", None, -1))
        self.pos_badvector_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Bad Vectors Replacement", None, -1))
        self.pos_bv_niterations_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Num. of max iterations", None, -1))
        self.pos_bv_method_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "localmean", None, -1))
        self.pos_bv_method_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "disk", None, -1))
        self.pos_bv_method_CB.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "distance", None, -1))
        self.pos_bv_kernel_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Kernel size", None, -1))
        self.pos_smth_factor_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "smoothing coeff. u, v", None, -1))
        self.pos_smoothing_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Vector Smoothing", None, -1))
        self.pos_fm_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "ex. rotCW, flipUD", None, -1))
        self.pos_fieldmanip_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Field Manipulations", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Output Mode", None, -1))
        self.pos_output_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "simple", None, -1))
        self.pos_output_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "extended", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PosPage), QtWidgets.QApplication.translate("MainWindow", "Post-Process", None, -1))
        self.process_savesettings_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Save Settings", None, -1))
        self.Main_tabs.setTabText(self.Main_tabs.indexOf(self.Process), QtWidgets.QApplication.translate("MainWindow", "Process", None, -1))
        self.freq_exp_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Experiment", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Directory", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Experiments", None, -1))
        self.freq_exp_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "experiments naming pattern", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "Runs", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Pattern", None, -1))
        self.freq_pat_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "files naming pattern", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Num. of Files", None, -1))
        self.freq_dir_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "path to the experiment directory", None, -1))
        self.freq_dir_TB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.freq_nf_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "number of files to use", None, -1))
        self.freq_run_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "runs naming pattern", None, -1))
        self.freq_load_from_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Load Experiment Settings From The Process Tab", None, -1))
        self.freq_analysis_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Analysis", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Acquisition Frequency", None, -1))
        self.freq_fs_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "fs", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Dimension Factor", None, -1))
        self.freq_dim_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "St=f*(dim_factor)", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "Frequency Limit", None, -1))
        self.freq_flim_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "highest frequency", None, -1))
        self.freq_pt_fft_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Perform Point FFT", None, -1))
        self.freq_pt_stft_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Perform Point STFT", None, -1))
        self.freq_gb_fft_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Perform Global FFT", None, -1))
        self.freq_gb_stft_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Perform Global STFT", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "STFT", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "Data per Segment", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Overlap", None, -1))
        self.freq_noverlap_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "overlap", None, -1))
        self.freq_nperseg_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "num. per segment", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Point Location", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "Mode            ", None, -1))
        self.freq_pt_loc_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Max Global Su", None, -1))
        self.freq_pt_loc_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Max Global Sv", None, -1))
        self.freq_pt_loc_CB.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Specified Point", None, -1))
        self.freq_pt_loc_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "x, y", None, -1))
        self.freq_load_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Load Settings", None, -1))
        self.freq_save_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Save Settings", None, -1))
        self.freq_run_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Run Progress", None, -1))
        self.freq_start_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.freq_stop_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Progress", None, -1))
        self.freq_progress_TE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Details of the run are shown here...", None, -1))
        self.Main_tabs.setTabText(self.Main_tabs.indexOf(self.FrequencyAnalysis), QtWidgets.QApplication.translate("MainWindow", "Freq. Analysis", None, -1))
        self.mdl_save_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Save Settings", None, -1))
        self.modal_ana_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Analysis", None, -1))
        self.mdl_nm_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Number of modes to save", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Method", None, -1))
        self.mdl_method_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Singular Value Decomposition", None, -1))
        self.mdl_method_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Snapshots Method", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Num. of Modes", None, -1))
        self.mdl_st_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Run Modal Analysis", None, -1))
        self.modal_rec_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Reconstruction", None, -1))
        self.mdl_rec_CB.setText(QtWidgets.QApplication.translate("MainWindow", "Perform Field Reconstruction", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Num. of Modes", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Num. of Snapshots", None, -1))
        self.mdl_rec_ns_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Number of snapshot to reconstruct", None, -1))
        self.mdl_rec_nm_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Number of modes to use for reconstruction", None, -1))
        self.modal_run_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Run Progress", None, -1))
        self.mdl_start_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.mdl_stop_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Progress", None, -1))
        self.mdl_progress_TE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Details of the run are shown here...", None, -1))
        self.modal_exp_GB.setTitle(QtWidgets.QApplication.translate("MainWindow", "Experiment", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Directory", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Experiments", None, -1))
        self.mdl_exp_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "experiments naming pattern", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Runs", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Pattern", None, -1))
        self.mdl_pat_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "files naming pattern", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Num. of Files", None, -1))
        self.mdl_dir_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "path to the experiment directory", None, -1))
        self.mdl_dir_TB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.mdl_nf_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Number of files to use", None, -1))
        self.mdl_run_LE.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "runs naming pattern", None, -1))
        self.mdl_load_from_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Load Experiment Settings From The Process Tab", None, -1))
        self.mdl_load_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Load Settings", None, -1))
        self.Main_tabs.setTabText(self.Main_tabs.indexOf(self.ModalAnalysis), QtWidgets.QApplication.translate("MainWindow", "Modal Analysis", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionLoad_Files.setText(QtWidgets.QApplication.translate("MainWindow", "Load Files", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionClear_Files.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Files", None, -1))
        self.actionLoad_Raw_Images.setText(QtWidgets.QApplication.translate("MainWindow", "Load Raw Images", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

