# +------------------------+                       
# | Created with ShipSnake |                       
# |                        |                       
# | Do not edit this file  |                       
# | directly. Insead       |                       
# | you should edit the    |                       
# | `shipsnake.toml` file. |                       
# +------------------------+    

import setuptools

try:
  with open("README.md", "r") as fh:
      long_description = fh.read()
except:
	long_description = "# Hello World\ntest...\n### Contributors\n- Cole Wilson\n### Contact\n<cole@colewilson.xyz> "

setuptools.setup(
    name="hello-test-cole",
    version="0.0.1",
		scripts=['bin/hello-test-cole'],
#		entry_points={
#			'console_scripts': ['hello-test-cole=hello-test-cole.__main__'],
#		},
    author="Cole Wilson",
    author_email="cole@colewilson.xyz",
    description="test...",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://google.com",
    packages=setuptools.find_packages(),
		install_requires=[''],
    classifiers=["Programming Language :: Python :: 3"],
    python_requires='>=3.6',
		package_data={"": [''],},
		license="",
		keywords='1 2 3 4 5',
)