# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from proto.google.fhir.proto.r4.core.codes_pb2 import (
    AppointmentStatusCode as proto___google___fhir___proto___r4___core___codes_pb2___AppointmentStatusCode,
    ParticipantRequiredCode as proto___google___fhir___proto___r4___core___codes_pb2___ParticipantRequiredCode,
    ParticipationStatusCode as proto___google___fhir___proto___r4___core___codes_pb2___ParticipationStatusCode,
)

from proto.google.fhir.proto.r4.core.datatypes_pb2 import (
    Code as proto___google___fhir___proto___r4___core___datatypes_pb2___Code,
    CodeableConcept as proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept,
    DateTime as proto___google___fhir___proto___r4___core___datatypes_pb2___DateTime,
    Extension as proto___google___fhir___proto___r4___core___datatypes_pb2___Extension,
    Id as proto___google___fhir___proto___r4___core___datatypes_pb2___Id,
    Identifier as proto___google___fhir___proto___r4___core___datatypes_pb2___Identifier,
    Instant as proto___google___fhir___proto___r4___core___datatypes_pb2___Instant,
    Meta as proto___google___fhir___proto___r4___core___datatypes_pb2___Meta,
    Narrative as proto___google___fhir___proto___r4___core___datatypes_pb2___Narrative,
    Period as proto___google___fhir___proto___r4___core___datatypes_pb2___Period,
    PositiveInt as proto___google___fhir___proto___r4___core___datatypes_pb2___PositiveInt,
    Reference as proto___google___fhir___proto___r4___core___datatypes_pb2___Reference,
    String as proto___google___fhir___proto___r4___core___datatypes_pb2___String,
    UnsignedInt as proto___google___fhir___proto___r4___core___datatypes_pb2___UnsignedInt,
    Uri as proto___google___fhir___proto___r4___core___datatypes_pb2___Uri,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Appointment(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class StatusCode(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        value: proto___google___fhir___proto___r4___core___codes_pb2___AppointmentStatusCode.ValueValue = ...

        @property
        def id(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

        @property
        def extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

        def __init__(self,
            *,
            value : typing___Optional[proto___google___fhir___proto___r4___core___codes_pb2___AppointmentStatusCode.ValueValue] = None,
            id : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
            extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"id",b"id"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"extension",b"extension",u"id",b"id",u"value",b"value"]) -> None: ...
    type___StatusCode = StatusCode

    class Participant(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class RequiredCode(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            value: proto___google___fhir___proto___r4___core___codes_pb2___ParticipantRequiredCode.ValueValue = ...

            @property
            def id(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

            @property
            def extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

            def __init__(self,
                *,
                value : typing___Optional[proto___google___fhir___proto___r4___core___codes_pb2___ParticipantRequiredCode.ValueValue] = None,
                id : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
                extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"id",b"id"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"extension",b"extension",u"id",b"id",u"value",b"value"]) -> None: ...
        type___RequiredCode = RequiredCode

        class StatusCode(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            value: proto___google___fhir___proto___r4___core___codes_pb2___ParticipationStatusCode.ValueValue = ...

            @property
            def id(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

            @property
            def extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

            def __init__(self,
                *,
                value : typing___Optional[proto___google___fhir___proto___r4___core___codes_pb2___ParticipationStatusCode.ValueValue] = None,
                id : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
                extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"id",b"id"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"extension",b"extension",u"id",b"id",u"value",b"value"]) -> None: ...
        type___StatusCode = StatusCode


        @property
        def id(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

        @property
        def extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

        @property
        def modifier_extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

        @property
        def type(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]: ...

        @property
        def actor(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Reference: ...

        @property
        def required(self) -> type___Appointment.Participant.RequiredCode: ...

        @property
        def status(self) -> type___Appointment.Participant.StatusCode: ...

        @property
        def period(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Period: ...

        def __init__(self,
            *,
            id : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
            extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
            modifier_extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
            type : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]] = None,
            actor : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference] = None,
            required : typing___Optional[type___Appointment.Participant.RequiredCode] = None,
            status : typing___Optional[type___Appointment.Participant.StatusCode] = None,
            period : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Period] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"id",b"id",u"period",b"period",u"required",b"required",u"status",b"status"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"actor",b"actor",u"extension",b"extension",u"id",b"id",u"modifier_extension",b"modifier_extension",u"period",b"period",u"required",b"required",u"status",b"status",u"type",b"type"]) -> None: ...
    type___Participant = Participant


    @property
    def id(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Id: ...

    @property
    def meta(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Meta: ...

    @property
    def implicit_rules(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Uri: ...

    @property
    def language(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Code: ...

    @property
    def text(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Narrative: ...

    @property
    def contained(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___any_pb2___Any]: ...

    @property
    def extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

    @property
    def modifier_extension(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]: ...

    @property
    def identifier(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Identifier]: ...

    @property
    def status(self) -> type___Appointment.StatusCode: ...

    @property
    def cancelation_reason(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept: ...

    @property
    def service_category(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]: ...

    @property
    def service_type(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]: ...

    @property
    def specialty(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]: ...

    @property
    def appointment_type(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept: ...

    @property
    def reason_code(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]: ...

    @property
    def reason_reference(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]: ...

    @property
    def priority(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___UnsignedInt: ...

    @property
    def description(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

    @property
    def supporting_information(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]: ...

    @property
    def start(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Instant: ...

    @property
    def end(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Instant: ...

    @property
    def minutes_duration(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___PositiveInt: ...

    @property
    def slot(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]: ...

    @property
    def created(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___DateTime: ...

    @property
    def comment(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

    @property
    def patient_instruction(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

    @property
    def based_on(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]: ...

    @property
    def participant(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Appointment.Participant]: ...

    @property
    def requested_period(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___google___fhir___proto___r4___core___datatypes_pb2___Period]: ...

    def __init__(self,
        *,
        id : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Id] = None,
        meta : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Meta] = None,
        implicit_rules : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Uri] = None,
        language : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Code] = None,
        text : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Narrative] = None,
        contained : typing___Optional[typing___Iterable[google___protobuf___any_pb2___Any]] = None,
        extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
        modifier_extension : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Extension]] = None,
        identifier : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Identifier]] = None,
        status : typing___Optional[type___Appointment.StatusCode] = None,
        cancelation_reason : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept] = None,
        service_category : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]] = None,
        service_type : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]] = None,
        specialty : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]] = None,
        appointment_type : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept] = None,
        reason_code : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___CodeableConcept]] = None,
        reason_reference : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]] = None,
        priority : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___UnsignedInt] = None,
        description : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
        supporting_information : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]] = None,
        start : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Instant] = None,
        end : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Instant] = None,
        minutes_duration : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___PositiveInt] = None,
        slot : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]] = None,
        created : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___DateTime] = None,
        comment : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
        patient_instruction : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
        based_on : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference]] = None,
        participant : typing___Optional[typing___Iterable[type___Appointment.Participant]] = None,
        requested_period : typing___Optional[typing___Iterable[proto___google___fhir___proto___r4___core___datatypes_pb2___Period]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"appointment_type",b"appointment_type",u"cancelation_reason",b"cancelation_reason",u"comment",b"comment",u"created",b"created",u"description",b"description",u"end",b"end",u"id",b"id",u"implicit_rules",b"implicit_rules",u"language",b"language",u"meta",b"meta",u"minutes_duration",b"minutes_duration",u"patient_instruction",b"patient_instruction",u"priority",b"priority",u"start",b"start",u"status",b"status",u"text",b"text"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"appointment_type",b"appointment_type",u"based_on",b"based_on",u"cancelation_reason",b"cancelation_reason",u"comment",b"comment",u"contained",b"contained",u"created",b"created",u"description",b"description",u"end",b"end",u"extension",b"extension",u"id",b"id",u"identifier",b"identifier",u"implicit_rules",b"implicit_rules",u"language",b"language",u"meta",b"meta",u"minutes_duration",b"minutes_duration",u"modifier_extension",b"modifier_extension",u"participant",b"participant",u"patient_instruction",b"patient_instruction",u"priority",b"priority",u"reason_code",b"reason_code",u"reason_reference",b"reason_reference",u"requested_period",b"requested_period",u"service_category",b"service_category",u"service_type",b"service_type",u"slot",b"slot",u"specialty",b"specialty",u"start",b"start",u"status",b"status",u"supporting_information",b"supporting_information",u"text",b"text"]) -> None: ...
type___Appointment = Appointment
