"""App settings."""
import os

# region app

VAR_FLASK_RUN_PORT = 'FLASK_RUN_PORT'
DEFAULT_FLASK_RUN_PORT = 8000
FLASK_RUN_PORT = os.getenv(VAR_FLASK_RUN_PORT, DEFAULT_FLASK_RUN_PORT)

VAR_FLASK_DEBUG = 'FLASK_DEBUG'
DEFAULT_FLASK_DEBUG = 1
FLASK_DEBUG = os.getenv(VAR_FLASK_DEBUG, DEFAULT_FLASK_DEBUG)

VAR_FLASK_HOST = 'FLASK_HOST'
DEFAULT_FLASK_HOST = None
FLASK_HOST = os.getenv(VAR_FLASK_HOST, DEFAULT_FLASK_HOST)

# endregion app

# region telemetry

VAR_LOG_FILE_NAME = 'CGME_LOG_FILE'
DEFAULT_LOG_FILE_NAME = 'cgme.log'
LOG_FILE_NAME = os.getenv(VAR_LOG_FILE_NAME, DEFAULT_LOG_FILE_NAME)

VAR_INSTRUMENTATION_KEY = 'INSTRUMENTATION_KEY'
DEFAULT_INSTRUMENTATION_KEY = None
INSTRUMENTATION_KEY = os.getenv(VAR_INSTRUMENTATION_KEY)

# endregion telemetry
